// AUTO-DRAFT from curl/curl PR #4735
ngtcp2_settings settings;
  SSL_CTX *sslctx;
  SSL *ssl;
  uint8_t *rx_secret; /* malloced */  // <<< BUG ANCHOR
  uint8_t *tx_secret; /* points into the above buffer */
  size_t rx_secretlen;
  struct quic_handshake crypto_data[3];
  /* the last TLS alert description generated by the local endpoint */
  uint8_t tls_alert;
